{% set python_min = "3.10" %}
{% set name = "ParProcCo" %}
{% set lname = name | lower %}
{% set version = "2.2.0" %}

package:
  name: {{ lname }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ lname[0] }}/{{ lname }}/{{ lname }}-{{ version }}.tar.gz
  sha256: e80e11cc595fea1d9466d3100667bad0e1bacb8d6d6878e68cfebb56cf342eb8

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - h5py >=3
    - pydantic >=2
    - pyyaml
    - requests

test:
  imports:
    - {{ name }}
  source_files:
    - example
    - tests
  requires:
    - parameterized
    - pytest
    - python {{ python_min }}
  commands:
    - pytest -vv tests/

about:
  home: https://github.com/DiamondLightSource/{{ name }}
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Parallel Processing Coordinator'

  description: Parallel Processing Coordinator. Splits dataset processing to run parallel cluster jobs and aggregates outputs.
  doc_url: https://github.com/DiamondLightSource/{{ name }}/blob/master/README.md
  dev_url: https://github.com/DiamondLightSource/{{ name }}

extra:
  recipe-maintainers:
    - PeterC-DLS
    - VictoriaBeilsten-Edmands
