{% set python_min = '3.10' %}
{% set name = "ParProcCo" %}
{% set lname = name | lower %}
{% set version = "2.1.2" %}

package:
  name: {{ lname }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ lname[0] }}/{{ lname }}/{{ lname }}-{{ version }}.tar.gz
  sha256: aa4691c0c1de7cbd5db9411a2a935a7da6f37d4d70e41a3e4175229f314f2c66

build:
  number: 1
  script: "{{ PYTHON }} -m pip install . -vv"
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - h5py >=3
    - pydantic >=2
    - pyyaml
    - requests

test:
  imports:
    - {{ name }}
  source_files:
    - example
    - tests
  requires:
    - parameterized
    - pytest
    - python {{ python_min }}
  commands:
    - pytest -vv tests/

about:
  home: https://github.com/DiamondLightSource/{{ name }}
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Parallel Processing Coordinator'

  description:
    Parallel Processing Coordinator. Splits dataset processing to run parallel
    cluster jobs and aggregates outputs.
  doc_url: https://github.com/DiamondLightSource/{{ name }}/blob/master/README.md
  dev_url: https://github.com/DiamondLightSource/{{ name }}

extra:
  recipe-maintainers:
    - PeterC-DLS
    - VictoriaBeilsten-Edmands
